// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"posts_commets_service/internal/domain/models"
)

type InputComment struct {
	PostID          int    `json:"postID"`
	UserID          int    `json:"userID"`
	Text            string `json:"text"`
	ParentCommentID *int   `json:"parentCommentID,omitempty"`
}

type InputPost struct {
	UserID       int    `json:"userID"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	CommentBlock *bool  `json:"commentBlock,omitempty"`
}

type InputUser struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type PostsPage struct {
	Posts  []*models.Post `json:"posts"`
	NextID *int           `json:"nextID,omitempty"`
}

type Query struct {
}
